services: 
- type: web
  name: englang
  env: python
  buildCommand: "./build.sh"        # ensure it's a string
  startCommand: cd main && gunicorn main.wsgi:application
  repo: https://github.com/polinadrrrr/Englang_for_render # optional
  # plan: standard # optional
  healthCheckPath: /
  # autoDeploy: false             # optional
  envVars:
  - key: DJANGO_SECRET_KEY
    generateValue: true       # will generate a base64-encoded 256-bit secret